server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vulnerableapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: vulnerableapp
          app: VulnerableApp
          environment: dev
          category: general
          module: general
          __path__: /var/log/vulnerableapp/*.txt
    pipeline_stages:
      - match:
          selector: '{job="vulnerableapp"} |~ "(?i)(auth\\.login|auth\\.dashboard|evento de autenticacion)"'
          stages:
            - static_labels:
                category: security
                module: authentication

      - match:
          selector: '{job="vulnerableapp"} |~ "(?i)(comment\\.addcomment|comment\\.index)"'
          stages:
            - static_labels:
                category: audit
                module: content

      - match:
          selector: '{job="vulnerableapp"} |~ "(?i)(api\\.getuser|api\\.getallusers)"'
          stages:
            - static_labels:
                category: security
                module: api